# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-CgiAppAPI
version:      1.01
version_from: 
installdirs:  site
requires:
    CGI::Builder:                  0.9

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
