# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-CgiAppAPI
version:      1.26
version_from: lib/CGI/Builder/CgiAppAPI.pm
installdirs:  site
requires:
    CGI::Builder:                  1.3
    Object::groups:                2
    Object::props:                 2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
